// Generated by CoffeeScript 1.9.2
(function() {
  var pongular;

  pongular = require('pongular').pongular;

  module.exports = pongular.module('pong-q', []).service('$q', function() {
    return require('q');
  }).service('$promise', function($q) {
    return function(fn) {
      var d;
      d = $q.defer();
      fn(d);
      return d.promise;
    };
  });

}).call(this);
